#include <ruby.h>
#include <gr.h>

double* rb_ar_2_dbl_ar(VALUE);
int* rb_ar_2_int_ar(VALUE);
static VALUE opengks(VALUE);
static VALUE closegks(VALUE);
static VALUE inqdspsize(VALUE,VALUE,VALUE,VALUE,VALUE);
static VALUE openws(VALUE,VALUE,VALUE,VALUE);
static VALUE closews(VALUE,VALUE);
static VALUE activatews(VALUE,VALUE);
static VALUE deactivatews(VALUE,VALUE);
static VALUE clearws(VALUE);
static VALUE updatews(VALUE);
static VALUE polyline(VALUE,VALUE,VALUE);
static VALUE polymarker(VALUE,VALUE,VALUE);
static VALUE text(VALUE,VALUE,VALUE,VALUE);
static VALUE inqtext(VALUE,VALUE,VALUE,VALUE,VALUE,VALUE);
static VALUE fillarea(VALUE,VALUE,VALUE);
static VALUE cellarray(VALUE,VALUE,VALUE,VALUE,VALUE,VALUE,VALUE,VALUE,VALUE,VALUE,VALUE,VALUE);
static VALUE gdp(VALUE,VALUE,VALUE,VALUE,VALUE,VALUE,VALUE);
static VALUE spline(VALUE,VALUE,VALUE,VALUE,VALUE,VALUE);
static VALUE gridit(VALUE,VALUE,VALUE,VALUE,VALUE,VALUE,VALUE,VALUE,VALUE,VALUE);
static VALUE setlinetype(VALUE,VALUE);
static VALUE inqlinetype(VALUE,VALUE);
static VALUE setlinewidth(VALUE,VALUE);
static VALUE inqlinewidth(VALUE,VALUE);
static VALUE setlinecolorind(VALUE,VALUE);
static VALUE inqlinecolorind(VALUE,VALUE);
static VALUE setmarkertype(VALUE,VALUE);
static VALUE inqmarkertype(VALUE,VALUE);
static VALUE setmarkersize(VALUE,VALUE);
static VALUE setmarkercolorind(VALUE,VALUE);
static VALUE inqmarkercolorind(VALUE,VALUE);
static VALUE settextfontprec(VALUE,VALUE,VALUE);
static VALUE setcharexpan(VALUE,VALUE);
static VALUE setcharspace(VALUE,VALUE);
static VALUE settextcolorind(VALUE,VALUE);
static VALUE setcharheight(VALUE,VALUE);
static VALUE setcharup(VALUE,VALUE,VALUE);
static VALUE settextpath(VALUE,VALUE);
static VALUE settextalign(VALUE,VALUE,VALUE);
static VALUE setfillintstyle(VALUE,VALUE);
static VALUE setfillstyle(VALUE,VALUE);
static VALUE setfillcolorind(VALUE,VALUE);
static VALUE setcolorrep(VALUE,VALUE,VALUE,VALUE,VALUE);
static VALUE setwindow(VALUE,VALUE,VALUE,VALUE,VALUE);
static VALUE inqwindow(VALUE,VALUE,VALUE,VALUE,VALUE);
static VALUE setviewport(VALUE,VALUE,VALUE,VALUE,VALUE);
static VALUE inqviewport(VALUE,VALUE,VALUE,VALUE,VALUE);
static VALUE selntran(VALUE,VALUE);
static VALUE setclip(VALUE,VALUE);
static VALUE setwswindow(VALUE,VALUE,VALUE,VALUE,VALUE);
static VALUE setwsviewport(VALUE,VALUE,VALUE,VALUE,VALUE);
static VALUE createseg(VALUE,VALUE);
static VALUE copysegws(VALUE,VALUE);
static VALUE redrawsegws(VALUE);
static VALUE setsegtran(VALUE,VALUE,VALUE,VALUE,VALUE,VALUE,VALUE,VALUE,VALUE);
static VALUE closeseg(VALUE);
static VALUE emergencyclosegks(VALUE);
static VALUE updategks(VALUE);
static VALUE setspace(VALUE,VALUE,VALUE,VALUE,VALUE);
static VALUE inqspace(VALUE,VALUE,VALUE,VALUE,VALUE);
static VALUE setscale(VALUE,VALUE);
static VALUE inqscale(VALUE,VALUE);
static VALUE textext(VALUE,VALUE,VALUE,VALUE);
static VALUE inqtextext(VALUE,VALUE,VALUE,VALUE,VALUE,VALUE);
static VALUE axes(VALUE,VALUE,VALUE,VALUE,VALUE,VALUE,VALUE,VALUE);
//static VALUE axeslbl(VALUE,VALUE,VALUE,VALUE,VALUE,VALUE,VALUE,VALUE,VALUE);
static VALUE grid(VALUE,VALUE,VALUE,VALUE,VALUE,VALUE,VALUE);
static VALUE grid3d(VALUE,VALUE,VALUE,VALUE,VALUE,VALUE,VALUE,VALUE,VALUE,VALUE);
static VALUE verrorbars(VALUE,VALUE,VALUE,VALUE,VALUE);
static VALUE herrorbars(VALUE,VALUE,VALUE,VALUE,VALUE);
static VALUE polyline3d(VALUE,VALUE,VALUE,VALUE);
static VALUE polymarker3d(VALUE,VALUE,VALUE,VALUE);
static VALUE axes3d(VALUE,VALUE,VALUE,VALUE,VALUE,VALUE,VALUE,VALUE,VALUE,VALUE,VALUE);
static VALUE titles3d(VALUE,VALUE,VALUE,VALUE);
static VALUE surface(VALUE,VALUE,VALUE,VALUE,VALUE);
static VALUE contour(VALUE,VALUE,VALUE,VALUE,VALUE,VALUE);
static VALUE tricontour(VALUE,VALUE,VALUE,VALUE,VALUE,VALUE,VALUE);
static VALUE hexbin(VALUE,VALUE,VALUE,VALUE,VALUE);
static VALUE setcolormap(VALUE,VALUE);
static VALUE inqcolormap(VALUE,VALUE);
static VALUE colorbar(VALUE);
static VALUE inqcolor(VALUE,VALUE,VALUE);
static VALUE inqcolorfromrgb(VALUE,VALUE,VALUE,VALUE);
static VALUE hsvtorgb(VALUE,VALUE,VALUE,VALUE,VALUE,VALUE,VALUE);
static VALUE tick(VALUE,VALUE,VALUE);
static VALUE validaterange(VALUE,VALUE,VALUE);
static VALUE adjustlimits(VALUE,VALUE,VALUE);
static VALUE adjustrange(VALUE,VALUE,VALUE);
static VALUE beginprint(VALUE,VALUE);
static VALUE beginprintext(VALUE,VALUE,VALUE,VALUE,VALUE);
static VALUE endprint(VALUE);
static VALUE ndctowc(VALUE,VALUE,VALUE);
static VALUE wctondc(VALUE,VALUE,VALUE);
static VALUE wc3towc(VALUE,VALUE,VALUE,VALUE);
static VALUE drawrect(VALUE,VALUE,VALUE,VALUE,VALUE);
static VALUE fillrect(VALUE,VALUE,VALUE,VALUE,VALUE);
static VALUE drawarc(VALUE,VALUE,VALUE,VALUE,VALUE,VALUE,VALUE);
static VALUE fillarc(VALUE,VALUE,VALUE,VALUE,VALUE,VALUE,VALUE);
//static VALUE drawpath(VALUE,VALUE,VALUE,VALUE,VALUE);
static VALUE setarrowstyle(VALUE,VALUE);
static VALUE setarrowsize(VALUE,VALUE);
static VALUE drawarrow(VALUE,VALUE,VALUE,VALUE,VALUE);
//static VALUE readimage(VALUE,VALUE,VALUE,VALUE,VALUE);
static VALUE drawimage(VALUE,VALUE,VALUE,VALUE,VALUE,VALUE,VALUE,VALUE,VALUE);
static VALUE importgraphics(VALUE,VALUE);
static VALUE setshadow(VALUE,VALUE,VALUE,VALUE);
static VALUE settransparency(VALUE,VALUE);
//static VALUE setcoordxform(VALUE,VALUE);
static VALUE begingraphics(VALUE,VALUE);
static VALUE endgraphics(VALUE);
static VALUE getgraphics(VALUE);
static VALUE drawgraphics(VALUE,VALUE);
static VALUE mathtex(VALUE,VALUE,VALUE,VALUE);
static VALUE inqmathtex(VALUE,VALUE,VALUE,VALUE,VALUE,VALUE);
static VALUE beginselection(VALUE,VALUE,VALUE);
static VALUE endselection(VALUE);
static VALUE moveselection(VALUE,VALUE,VALUE);
static VALUE resizeselection(VALUE,VALUE,VALUE,VALUE);
static VALUE inqbbox(VALUE,VALUE,VALUE,VALUE,VALUE);
static VALUE precision(VALUE);
static VALUE setregenflags(VALUE,VALUE);
static VALUE inqregenflags(VALUE);
static VALUE savestate(VALUE);
static VALUE restorestate(VALUE);
static VALUE selectcontext(VALUE,VALUE);
static VALUE destroycontext(VALUE,VALUE);
static VALUE uselinespec(VALUE,VALUE);
//static VALUE delaunay(VALUE,VALUE,VALUE,VALUE,VALUE,VALUE);
//static VALUE reducepoints(VALUE,VALUE,VALUE,VALUE,VALUE,VALUE,VALUE);
static VALUE trisurface(VALUE,VALUE,VALUE,VALUE);
static VALUE gradient(VALUE,VALUE,VALUE,VALUE,VALUE,VALUE,VALUE,VALUE);
static VALUE quiver(VALUE,VALUE,VALUE,VALUE,VALUE,VALUE,VALUE,VALUE);
/*
static VALUE interp2(VALUE,VALUE,VALUE,VALUE,VALUE,VALUE,VALUE,VALUE,VALUE,VALUE,VALUE,VALUE,VALUE);
static VALUE meta_args_t(VALUE,VALUE);
static VALUE meta_args_delete(VALUE,VALUE);
static VALUE meta_args_push_arg(VALUE,VALUE,VALUE,VALUE);
static VALUE meta_args_push_arg_buf(VALUE,VALUE,VALUE,VALUE,VALUE);
static VALUE meta_args_push_kwarg(VALUE,VALUE,VALUE,VALUE,VALUE);
static VALUE meta_args_push_kwarg_buf(VALUE,VALUE,VALUE,VALUE,VALUE,VALUE);
static VALUE openmeta(VALUE,VALUE,VALUE);
static VALUE sendmeta(VALUE,VALUE,VALUE,VALUE);
static VALUE sendmeta_buf(VALUE,VALUE,VALUE,VALUE,VALUE);
static VALUE sendmeta_args(VALUE,VALUE,VALUE);
static VALUE closemeta(VALUE,VALUE);
*/
static VALUE version(VALUE);

void Init_grruby(){
  VALUE mGRruby=rb_define_module("GR");
  VALUE mGR3ruby=rb_define_module("GR3");

  rb_define_singleton_method(mGRruby,"opengks",opengks,0);
  rb_define_singleton_method(mGRruby,"closegks",closegks,0);
  rb_define_singleton_method(mGRruby,"inqdspsize",inqdspsize,4);
  rb_define_singleton_method(mGRruby,"openws",openws,3);
  rb_define_singleton_method(mGRruby,"closews",closews,1);
  rb_define_singleton_method(mGRruby,"activatews",activatews,1);
  rb_define_singleton_method(mGRruby,"deactivatews",deactivatews,1);
  rb_define_singleton_method(mGRruby,"clearws",clearws,0);
  rb_define_singleton_method(mGRruby,"updatews",updatews,0);
  rb_define_singleton_method(mGRruby,"polyline",polyline,2);
  rb_define_singleton_method(mGRruby,"polymarker",polymarker,2);
  rb_define_singleton_method(mGRruby,"text",text,3);
  rb_define_singleton_method(mGRruby,"inqtext",inqtext,5);
  rb_define_singleton_method(mGRruby,"fillarea",fillarea,2);
  rb_define_singleton_method(mGRruby,"cellarray",cellarray,11);
  rb_define_singleton_method(mGRruby,"gdp",gdp,6);
  rb_define_singleton_method(mGRruby,"spline",spline,5);
  rb_define_singleton_method(mGRruby,"gridit",gridit,9);
  rb_define_singleton_method(mGRruby,"setlinetype",setlinetype,1);
  rb_define_singleton_method(mGRruby,"inqlinetype",inqlinetype,1);
  rb_define_singleton_method(mGRruby,"setlinewidth",setlinewidth,1);
  rb_define_singleton_method(mGRruby,"inqlinewidth",inqlinewidth,1);
  rb_define_singleton_method(mGRruby,"setlinecolorind",setlinecolorind,1);
  rb_define_singleton_method(mGRruby,"inqlinecolorind",inqlinecolorind,1);
  rb_define_singleton_method(mGRruby,"setmarkertype",setmarkertype,1);
  rb_define_singleton_method(mGRruby,"inqmarkertype",inqmarkertype,1);
  rb_define_singleton_method(mGRruby,"setmarkersize",setmarkersize,1);
  rb_define_singleton_method(mGRruby,"setmarkercolorind",setmarkercolorind,1);
  rb_define_singleton_method(mGRruby,"inqmarkercolorind",inqmarkercolorind,1);
  rb_define_singleton_method(mGRruby,"settextfontprec",settextfontprec,2);
  rb_define_singleton_method(mGRruby,"setcharexpan",setcharexpan,1);
  rb_define_singleton_method(mGRruby,"setcharspace",setcharspace,1);
  rb_define_singleton_method(mGRruby,"settextcolorind",settextcolorind,1);
  rb_define_singleton_method(mGRruby,"setcharheight",setcharheight,1);
  rb_define_singleton_method(mGRruby,"setcharup",setcharup,2);
  rb_define_singleton_method(mGRruby,"settextpath",settextpath,1);
  rb_define_singleton_method(mGRruby,"settextalign",settextalign,2);
  rb_define_singleton_method(mGRruby,"setfillintstyle",setfillintstyle,1);
  rb_define_singleton_method(mGRruby,"setfillstyle",setfillstyle,1);
  rb_define_singleton_method(mGRruby,"setfillcolorind",setfillcolorind,1);
  rb_define_singleton_method(mGRruby,"setcolorrep",setcolorrep,4);
  rb_define_singleton_method(mGRruby,"setwindow",setwindow,4);
  rb_define_singleton_method(mGRruby,"inqwindow",inqwindow,4);
  rb_define_singleton_method(mGRruby,"setviewport",setviewport,4);
  rb_define_singleton_method(mGRruby,"inqviewport",inqviewport,4);
  rb_define_singleton_method(mGRruby,"selntran",selntran,1);
  rb_define_singleton_method(mGRruby,"setclip",setclip,1);
  rb_define_singleton_method(mGRruby,"setwswindow",setwswindow,4);
  rb_define_singleton_method(mGRruby,"setwsviewport",setwsviewport,4);
  rb_define_singleton_method(mGRruby,"createseg",createseg,1);
  rb_define_singleton_method(mGRruby,"copysegws",copysegws,1);
  rb_define_singleton_method(mGRruby,"redrawsegws",redrawsegws,0);
  rb_define_singleton_method(mGRruby,"setsegtran",setsegtran,8);
  rb_define_singleton_method(mGRruby,"closeseg",closeseg,0);
  rb_define_singleton_method(mGRruby,"emergencyclosegks",emergencyclosegks,0);
  rb_define_singleton_method(mGRruby,"updategks",updategks,0);
  rb_define_singleton_method(mGRruby,"setspace",setspace,4);
  rb_define_singleton_method(mGRruby,"inqspace",inqspace,4);
  rb_define_singleton_method(mGRruby,"setscale",setscale,1);
  rb_define_singleton_method(mGRruby,"inqscale",inqscale,1);
  rb_define_singleton_method(mGRruby,"textext",textext,3);
  rb_define_singleton_method(mGRruby,"inqtextext",inqtextext,5);
  rb_define_singleton_method(mGRruby,"axes",axes,7);
  //rb_define_singleton_method(mGRruby,"axeslbl",axeslbl,8);
  rb_define_singleton_method(mGRruby,"grid",grid,6);
  rb_define_singleton_method(mGRruby,"grid3d",grid3d,9);
  rb_define_singleton_method(mGRruby,"verrorbars",verrorbars,4);
  rb_define_singleton_method(mGRruby,"herrorbars",herrorbars,4);
  rb_define_singleton_method(mGRruby,"polyline3d",polyline3d,3);
  rb_define_singleton_method(mGRruby,"polymarker3d",polymarker3d,3);
  rb_define_singleton_method(mGRruby,"axes3d",axes3d,10);
  rb_define_singleton_method(mGRruby,"titles3d",titles3d,3);
  rb_define_singleton_method(mGRruby,"surface",surface,4);
  rb_define_singleton_method(mGRruby,"contour",contour,5);
  rb_define_singleton_method(mGRruby,"tricontour",tricontour,6);
  rb_define_singleton_method(mGRruby,"hexbin",hexbin,4);
  rb_define_singleton_method(mGRruby,"setcolormap",setcolormap,1);
  rb_define_singleton_method(mGRruby,"inqcolormap",inqcolormap,1);
  rb_define_singleton_method(mGRruby,"colorbar",colorbar,0);
  rb_define_singleton_method(mGRruby,"inqcolor",inqcolor,2);
  rb_define_singleton_method(mGRruby,"inqcolorfromrgb",inqcolorfromrgb,3);
  rb_define_singleton_method(mGRruby,"hsvtorgb",hsvtorgb,6);
  rb_define_singleton_method(mGRruby,"tick",tick,2);
  rb_define_singleton_method(mGRruby,"validaterange",validaterange,2);
  rb_define_singleton_method(mGRruby,"adjustlimits",adjustlimits,2);
  rb_define_singleton_method(mGRruby,"adjustrange",adjustrange,2);
  rb_define_singleton_method(mGRruby,"beginprint",beginprint,1);
  rb_define_singleton_method(mGRruby,"beginprintext",beginprintext,4);
  rb_define_singleton_method(mGRruby,"endprint",endprint,0);
  rb_define_singleton_method(mGRruby,"ndctowc",ndctowc,2);
  rb_define_singleton_method(mGRruby,"wctondc",wctondc,2);
  rb_define_singleton_method(mGRruby,"wc3towc",wc3towc,3);
  rb_define_singleton_method(mGRruby,"drawrect",drawrect,4);
  rb_define_singleton_method(mGRruby,"fillrect",fillrect,4);
  rb_define_singleton_method(mGRruby,"drawarc",drawarc,6);
  rb_define_singleton_method(mGRruby,"fillarc",fillarc,6);
  //rb_define_singleton_method(mGRruby,"drawpath",drawpath,4);
  rb_define_singleton_method(mGRruby,"setarrowstyle",setarrowstyle,1);
  rb_define_singleton_method(mGRruby,"setarrowsize",setarrowsize,1);
  rb_define_singleton_method(mGRruby,"drawarrow",drawarrow,4);
  //rb_define_singleton_method(mGRruby,"readimage",readimage,4);
  rb_define_singleton_method(mGRruby,"drawimage",drawimage,8);
  rb_define_singleton_method(mGRruby,"importgraphics",importgraphics,1);
  rb_define_singleton_method(mGRruby,"setshadow",setshadow,3);
  rb_define_singleton_method(mGRruby,"settransparency",settransparency,1);
  //rb_define_singleton_method(mGRruby,"setcoordxform",setcoordxform,1);
  rb_define_singleton_method(mGRruby,"begingraphics",begingraphics,1);
  rb_define_singleton_method(mGRruby,"endgraphics",endgraphics,0);
  rb_define_singleton_method(mGRruby,"getgraphics",getgraphics,0);
  rb_define_singleton_method(mGRruby,"drawgraphics",drawgraphics,1);
  rb_define_singleton_method(mGRruby,"mathtex",mathtex,3);
  rb_define_singleton_method(mGRruby,"inqmathtex",inqmathtex,5);
  rb_define_singleton_method(mGRruby,"beginselection",beginselection,2);
  rb_define_singleton_method(mGRruby,"endselection",endselection,0);
  rb_define_singleton_method(mGRruby,"moveselection",moveselection,2);
  rb_define_singleton_method(mGRruby,"resizeselection",resizeselection,3);
  rb_define_singleton_method(mGRruby,"inqbbox",inqbbox,4);
  rb_define_singleton_method(mGRruby,"precision",precision,0);
  rb_define_singleton_method(mGRruby,"setregenflags",setregenflags,1);
  rb_define_singleton_method(mGRruby,"inqregenflags",inqregenflags,0);
  rb_define_singleton_method(mGRruby,"savestate",savestate,0);
  rb_define_singleton_method(mGRruby,"restorestate",restorestate,0);
  rb_define_singleton_method(mGRruby,"selectcontext",selectcontext,1);
  rb_define_singleton_method(mGRruby,"destroycontext",destroycontext,1);
  rb_define_singleton_method(mGRruby,"uselinespec",uselinespec,1);
  //rb_define_singleton_method(mGRruby,"delaunay",delaunay,5);
  //rb_define_singleton_method(mGRruby,"reducepoints",reducepoints,6);
  rb_define_singleton_method(mGRruby,"trisurface",trisurface,3);
  rb_define_singleton_method(mGRruby,"gradient",gradient,7);
  rb_define_singleton_method(mGRruby,"quiver",quiver,7);
  /*
  rb_define_singleton_method(mGRruby,"interp2",interp2,12);
  rb_define_singleton_method(mGRruby,"meta_args_t",meta_args_t,1);
  rb_define_singleton_method(mGRruby,"meta_args_delete",meta_args_delete,1);
  rb_define_singleton_method(mGRruby,"meta_args_push_arg",meta_args_push_arg,3);
  rb_define_singleton_method(mGRruby,"meta_args_push_arg_buf",meta_args_push_arg_buf,4);
  rb_define_singleton_method(mGRruby,"meta_args_push_kwarg",meta_args_push_kwarg,4);
  rb_define_singleton_method(mGRruby,"meta_args_push_kwarg_buf",meta_args_push_kwarg_buf,5);
  rb_define_singleton_method(mGRruby,"openmeta",openmeta,2);
  rb_define_singleton_method(mGRruby,"sendmeta",sendmeta,3);
  rb_define_singleton_method(mGRruby,"sendmeta_buf",sendmeta_buf,4);
  rb_define_singleton_method(mGRruby,"sendmeta_args",sendmeta_args,2);
  rb_define_singleton_method(mGRruby,"closemeta",closemeta,1);
*/
  rb_define_singleton_method(mGRruby,"version",version,0);
}


#include "GR_Libraries/GR.c"
